version: '0.0.1.{build}'

#init:
#- git config --global core.autocrlf input

environment:
  matrix:
  - QT5: C:\Qt\5.10.1\msvc2015
    COMPILER: C:\
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "true"
    use_widgets: "true"
    use_static: "true"


#matrix:
#  fast_finish: true

before_build:
- set PATH=%QT5%\bin;%PATH%
- if %use_static%==true (set USESTATIC=ON) else (set USESTATIC=OFF)
- if %use_gui%==true (set USEGUI=OFF) else (set USEGUI=ON)
- if %use_widgets%==true (set USEWIDGETS=OFF) else (set USEWIDGETS=ON)
- if %use_mingw%==true (set CMAKEGENERATOR="MinGW Makefiles") else (set CMAKEGENERATOR="NMake Makefiles")
- if %use_mingw%==true (set MAKEBUILDER=mingw32-make) else (set MAKEBUILDER=nmake)


#- if [%use_mingw%]==[true] (
#    set PATH=%COMPILER%\bin;%QT5%\bin;%PATH%
#  )
#  else (
#    set PATH=%QT5%\bin;%PATH%
#  )

build_script:
- mkdir .\build
- cd .\build
- if %use_cmake%==true (
    - cmake --version &&
    cmake -G %CMAKEGENERATOR% -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_STATIC_LIBS=%USESTATIC% -DNO_WIDGETS=%USEWIDGETS% -DNO_GUI=%USEGUI% ../ &&
    %MAKEBUILDER% &&
    cmake -G %CMAKEGENERATOR% -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_DEBUG_POSTFIX=d -DBUILD_STATIC_LIBS=ON ../ &&
    %MAKEBUILDER%
)
# TODO Implement msbuild