version: '0.0.1.{build}'

#init:
#- git config --global core.autocrlf input

environment:
  matrix:
  - QT5: C:\Qt\5.10.1\msvc2015
    COMPILER: C:\
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "true"
    use_widgets: "true"
    use_static: "true"


#matrix:
#  fast_finish: true

before_build:
- set PATH=%QT5%\bin;%PATH%
#- if [%use_mingw%]==[true] (
#    set PATH=%COMPILER%\bin;%QT5%\bin;%PATH%
#  )
#  else (
#    set PATH=%QT5%\bin;%PATH%
#  )

build_script:
- mkdir .\build
- cd .\build


# build library and tests
- if [%use_mingw%]==[true] (
    - cmake --version &&
    cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release .. &&
    make &&
    dir /s &&
    cd .\tests
  )
  else (
    - if [%use_cmake%]==[true] (
        - if [%use_static%]==[true] (
            - if [%use_gui%]==[true] (
                - if [%use_widgets%]==[true] (
                    - cmake --version &&
                    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_STATIC_LIBS=ON ../ &&
                    nmake
                    - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_STATIC_LIBS=ON ../ &&
                    nmake
                )
                else (
                    - cmake --version &&
                    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DNO_WIDGETS=ON -DBUILD_STATIC_LIBS=ON ../ &&
                    nmake
                    - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DNO_WIDGETS=ON -DBUILD_STATIC_LIBS=ON ../ &&
                    nmake
                )
            )
            else (
                - cmake --version &&
                cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DNO_GUI=ON -DBUILD_STATIC_LIBS=ON ../ &&
                nmake
                - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DNO_GUI=ON -DBUILD_STATIC_LIBS=ON ../ &&
                nmake
            )
        )
        else (
            - if [%use_gui%]==[true] (
                - if [%use_widgets%]==[true] (
                    - cmake --version &&
                    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_STATIC_LIBS=OFF ../ &&
                    nmake
                    - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_STATIC_LIBS=OFF ../ &&
                    nmake
                )
                else (
                    - cmake --version &&
                    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DNO_WIDGETS=ON -DBUILD_STATIC_LIBS=OFF ../ &&
                    nmake
                    - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DNO_WIDGETS=ON -DBUILD_STATIC_LIBS=OFF ../ &&
                    nmake
                )
            )
            else (
                - cmake --version &&
                cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DNO_GUI=ON -DBUILD_STATIC_LIBS=OFF ../ &&
                nmake
                - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DNO_GUI=ON -DBUILD_STATIC_LIBS=OFF ../ &&
                nmake
            )
        )
    )
    else(
        - echo "TODO Implement msbuild"
    )
  )