version: '0.0.1.{build}'

environment:
  matrix:
  - QT5: C:\Qt\5.10.1\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "true"
    use_widgets: "true"
    use_static: "true"
  - QT5: C:\Qt\5.10.1\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "true"
    use_widgets: "true"
    use_static: "false"
  - QT5: C:\Qt\5.10.1\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "true"
    use_widgets: "false"
    use_static: "true"
  - QT5: C:\Qt\5.10.1\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "true"
    use_widgets: "false"
    use_static: "false"
  - QT5: C:\Qt\5.10.1\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "false"
    use_widgets: "false"
    use_static: "true"
  - QT5: C:\Qt\5.10.1\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "false"
    use_widgets: "false"
    use_static: "false"
  - QT5: C:\Qt\5.10.1\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "true"
    use_widgets: "true"
    use_static: "true"
  - QT5: C:\Qt\5.10.1\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "true"
    use_widgets: "true"
    use_static: "false"
  - QT5: C:\Qt\5.10.1\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "true"
    use_widgets: "false"
    use_static: "true"
  - QT5: C:\Qt\5.10.1\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "true"
    use_widgets: "false"
    use_static: "false"
  - QT5: C:\Qt\5.10.1\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "false"
    use_widgets: "false"
    use_static: "true"
  - QT5: C:\Qt\5.10.1\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_cmake: "true"
    use_mingw: "false"
    use_gui: "false"
    use_widgets: "false"
    use_static: "false"
  


matrix:
  fast_finish: true

before_build:
- set PATH=%QT5%\bin;%PATH%
- if not %use_mingw%==true set PATH=%COMPILER%\bin;%QT5%\bin;%PATH%
- if not %use_mingw%==true call "%COMPILER%\vcvarsall.bat" %platform%
- if %use_static%==true (set USESTATIC=ON) else (set USESTATIC=OFF)
- if %use_gui%==true (set USEGUI=OFF) else (set USEGUI=ON)
- if %use_widgets%==true (set USEWIDGETS=OFF) else (set USEWIDGETS=ON)
- if %use_mingw%==true (set CMAKEGENERATOR="MinGW Makefiles") else (set CMAKEGENERATOR="NMake Makefiles")
- if %use_mingw%==true (set MAKEBUILDER=mingw32-make) else (set MAKEBUILDER=nmake)
- if %platform%==x86 (set TESTOUTPUTFOLDER=x86) else (set TESTOUTPUTFOLDER=x64)

build_script:
- mkdir .\build
- cd .\build
- if %use_cmake%==true (
    cmake --version &&
    cmake -G %CMAKEGENERATOR% -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_TESTS=ON -DBUILD_STATIC_LIBS=%USESTATIC% -DNO_WIDGETS=%USEWIDGETS% -DNO_GUI=%USEGUI% ../ &&
    %MAKEBUILDER% &&
    cmake -G %CMAKEGENERATOR% -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_TESTS=ON -DCMAKE_DEBUG_POSTFIX=d -DBUILD_STATIC_LIBS=%USESTATIC% -DNO_WIDGETS=%USEWIDGETS% -DNO_GUI=%USEGUI% ../ &&
    %MAKEBUILDER%)

test_script:
- If NOT exist "%TESTOUTPUTFOLDER%/bin" (appveyor exit)
- cd %TESTOUTPUTFOLDER%/bin
- set PATH=../lib;%PATH%
- for %%a in (*.exe) do %%a -xunitxml >> testsResults.xml

after_test:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testsResults.xml))