version: '0.0.1.{build}'

environment:
  matrix:
  - QT5: C:\Qt\5.10.1\mingw53_32
    COMPILER: C:\MinGW
    platform: x86
    use_mingw: "true"
    use_gui: "true"
    use_widgets: "true"
    use_static: "true"

matrix:
  fast_finish: true

before_build:
- set PATH=%COMPILER%\bin;%QT5%\bin;%PATH%
- if not %use_mingw%==true call "%COMPILER%\vcvarsall.bat" %platform%
- if %use_static%==true (set USESTATIC=ON) else (set USESTATIC=OFF)
- if %use_gui%==true (set USEGUI=OFF) else (set USEGUI=ON)
- if %use_widgets%==true (set USEWIDGETS=OFF) else (set USEWIDGETS=ON)
- if %use_mingw%==true (set CMAKEGENERATOR="MinGW Makefiles") else (set CMAKEGENERATOR="NMake Makefiles")
- if %use_mingw%==true (set MAKEBUILDER=mingw32-make) else (set MAKEBUILDER=nmake)
- if %use_mingw%==true set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
- if %platform%==x86 (set TESTOUTPUTFOLDER=x86) else (set TESTOUTPUTFOLDER=x64)

build_script:
- mkdir .\build 
- cd .\build
- cmake --version &&
    cmake -G %CMAKEGENERATOR% -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_TESTS=ON -DBUILD_STATIC_LIBS=%USESTATIC% -DNO_WIDGETS=%USEWIDGETS% -DNO_GUI=%USEGUI% ../ &&
    %MAKEBUILDER%
    
test_script:
- If NOT exist "%TESTOUTPUTFOLDER%/bin" (appveyor exit)
- cd %TESTOUTPUTFOLDER%/bin
- set PATH=../lib;%PATH%
- for %%a in (*.exe) do (%%a -xml > %%a_tstres.xml & set preventFail = 1)

on_finish:
- ps: if (Test-Path ".\testResults.xml") {(new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testResults.xml));}