version: '0.0.1.{build}'

environment:
  matrix:
  - QT5: C:\Qt\5.10.1\mingw53_32
    COMPILER: C:\MinGW
    platform: x86
    use_mingw: "true"
    use_gui: "true"
    use_widgets: "true"
    use_static: "true"

matrix:
  fast_finish: true

before_build:
- set PATH=%COMPILER%\bin;%QT5%\bin;%PATH%
- if not %use_mingw%==true call "%COMPILER%\vcvarsall.bat" %platform%
- if %use_static%==true (set USESTATIC=ON) else (set USESTATIC=OFF)
- if %use_gui%==true (set USEGUI=OFF) else (set USEGUI=ON)
- if %use_widgets%==true (set USEWIDGETS=OFF) else (set USEWIDGETS=ON)
- if %use_mingw%==true (set CMAKEGENERATOR="MinGW Makefiles") else (set CMAKEGENERATOR="NMake Makefiles")
- if %use_mingw%==true (set MAKEBUILDER=mingw32-make) else (set MAKEBUILDER=nmake)
- if %use_mingw%==true set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
- if %platform%==x86 (set TESTOUTPUTFOLDER=x86) else (set TESTOUTPUTFOLDER=x64)

build_script:
- mkdir .\build 
- cd .\build
- cmake --version &&
    cmake -G %CMAKEGENERATOR% -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_TESTS=ON -DBUILD_STATIC_LIBS=%USESTATIC% -DNO_WIDGETS=%USEWIDGETS% -DNO_GUI=%USEGUI% ../ &&
    %MAKEBUILDER%

after_build:
- set PATH=%PATH:%COMPILER%\bin;=%
- if %use_mingw%==true set PATH=C:\Program Files\Git\usr\bin;%PATH%

test_script:
- If NOT exist "%TESTOUTPUTFOLDER%/bin" (appveyor exit)
- cd %TESTOUTPUTFOLDER%/bin
- set PATH=../lib;%PATH%
- for %%a in (*.exe) do (%%a -xml > %%a_tstres.xml & set preventFail = 1)
- ps: '$xmlOut = new-object System.Xml.XmlDocument;
    $xmlOut.AppendChild($xmlOut.CreateXmlDeclaration("1.0","UTF-8",$null));
    $rootXmlOut = $xmlOut.CreateElement("testsuites");
    $xmlOut.AppendChild($rootXmlOut);
    $totalPass = 0;
    $totalFail = 0;
    $totalError = 0;
    $totalSkip = 0;
    $totalTime = 0;
    $XmlDocument = $null;
    $crashMessage = $null;
    Get-ChildItem ".\" -Filter "*_tstres.xml" | Foreach-Object {
        $localPass = 0;
        $localFail = 0;
        $localError = 0;
        $localSkip = 0;
        $localTime = 0;
        $currentFilePath = $_.FullName;
        if([bool]((Get-Content -Path $currentFilePath) -as [xml])){
            [xml]$XmlDocument = (Get-Content -Path $currentFilePath) -as [xml];
        }
        else{
            $rawFilecontent = [IO.File]::ReadAllText($currentFilePath);
        }
    };'