name: Standalone Modules
on: 
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '.travis.yml'
      - 'docs/**'
      - '**.markdown'
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches:
      - master
      - dev
    paths-ignore:
      - '.travis.yml'
      - 'docs/**'
      - '**.markdown'
      - '**.md'
      - 'LICENSE'
jobs:
    build:
        name: Build and Test ${{ matrix.modules.friendly_name }} Qt ${{ matrix.qt_ver }}
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
              qt_ver: [5.15.2,6.0.2]
              modules:
                - { friendly_name: RoleMaskProxyModel, rolemaskproxy: ON, insertproxy: OFF, modelserialisation: OFF, rootindexproxy: OFF}
                - { friendly_name: InsertProxyModel, rolemaskproxy: OFF, insertproxy: ON, modelserialisation: OFF, rootindexproxy: OFF}
                - { friendly_name: ModelSerialisation, rolemaskproxy: OFF, insertproxy: OFF, modelserialisation: ON, rootindexproxy: OFF}
                - { friendly_name: RootIndexProxyModel, rolemaskproxy: OFF, insertproxy: OFF, modelserialisation: OFF, rootindexproxy: ON}
        steps:
          - name: Install Qt
            uses: jurplel/install-qt-action@v2
            with:
              version: ${{ matrix.qt_ver }}
          - name: Git Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: Create Build Directory
            shell: pwsh
            run: |
              mkdir build
              cd build
              mkdir debug
              mkdir release
          - name: Install Linux Dependencies
            run: |
              sudo apt-get update -y
              sudo apt-get install libxcb-icccm4 libxcb-xkb1 libxcb-icccm4 libxcb-image0 libxcb-render-util0 libxcb-randr0 libxcb-keysyms1 libxcb-xinerama0 libxcb-xinput-dev
              export PATH=$PATH:$PWD/build/installed/lib
              export PATH=$PATH:$PWD/build/installed/bin
          - name: ${{ matrix.modules.friendly_name }} Qt${{ matrix.qt_ver }}
            shell: pwsh
            run: |
              cd build/debug
              cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_DEBUG_POSTFIX=d -DBUILD_TESTING=ON -DTEST_OUTPUT_XML=ON -DBUILD_EXAMPLES=ON -DBUILD_ROOTINDEXPROXY=${{ matrix.modules.rootindexproxy }} -DBUILD_ROLEMASKPROXY=${{ matrix.modules.rolemaskproxy }} -DBUILD_INSERTPROXY=${{ matrix.modules.insertproxy }} -DBUILD_MODELSERIALISATION=${{ matrix.modules.modelserialisation }} -DBUILD_STATIC_LIBS=OFF -DCMAKE_INSTALL_PREFIX="../installed" ../../
              cmake --build .
              cmake --build . --target install
              cd ../release
              cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_TESTING=ON -DTEST_OUTPUT_XML=ON -DBUILD_EXAMPLES=ON -DBUILD_ROOTINDEXPROXY=${{ matrix.modules.rootindexproxy }} -DBUILD_ROLEMASKPROXY=${{ matrix.modules.rolemaskproxy }} -DBUILD_INSERTPROXY=${{ matrix.modules.insertproxy }} -DBUILD_MODELSERIALISATION=${{ matrix.modules.modelserialisation }} -DBUILD_STATIC_LIBS=OFF -DCMAKE_INSTALL_PREFIX="../installed" ../../
              cmake --build .
              cmake --build . --target install
          - name: Debug Test
            id: rundebugtests
            continue-on-error: true
            uses: GabrielBB/xvfb-action@v1
            with:
              working-directory: ./build/debug
              run: cmake --build . --target test
          - name: Release Test
            id: runreleasetests
            uses: GabrielBB/xvfb-action@v1
            with:
              working-directory: ./build/release
              run: cmake --build . --target test
          - name: Prepare Test Report
            if: ${{ always() && (steps.rundebugtests.outcome == 'failure' || steps.runreleasetests.outcome == 'failure') }}
            uses: ./ci/processtestresults
            with:
                qt-tests: build/TestResults
                junit-output: build/TestResults/junitresult.xml
                html-output: build/TestResults/testsreport.html
          - name: Publish Test Report
            if: ${{ always() && (steps.rundebugtests.outcome == 'failure' || steps.runreleasetests.outcome == 'failure') }}
            uses: actions/upload-artifact@v2
            with:
                name: ${{ matrix.modules.friendly_name }}-Qt${{ matrix.qt_ver }}
                path: |
                  build/TestResults/junitresult.xml
                  build/TestResults/testsreport.html