name: clang-format Check
on: 
  push:
    branches:
      - master
      - dev
      - bugfix
      - ci_admin
    paths-ignore:
      - '.travis.yml'
      - '.appveyor.yml'
      - 'modelutilities.pri'
      - 'docs/**'
      - '**.markdown'
      - '**.md'
      - 'LICENSE'
      - '**CMakeLists.txt'
      - 'cmake/**'
  pull_request_target:
    paths-ignore:
      - '.travis.yml'
      - '.appveyor.yml'
      - 'modelutilities.pri'
      - 'docs/**'
      - '**.markdown'
      - '**.md'
      - 'LICENSE'
      - '**CMakeLists.txt'
      - 'cmake/**'
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.11.0