name: Ubuntu
on: 
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '.travis.yml'
      - '.appveyor.yml'
      - 'modelutilities.pri'
      - 'docs/**'
      - '**.markdown'
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches:
      - master
      - dev
    paths-ignore:
      - '.travis.yml'
      - '.appveyor.yml'
      - 'modelutilities.pri'
      - 'docs/**'
      - '**.markdown'
      - '**.md'
      - 'LICENSE'
jobs:
    build:
        name: Latest Ubuntu Build
        runs-on: ubuntu-latest
        strategy:
          matrix:
              qt_ver: [5.15.2,6.0.2]
              static_lib: [OFF,ON]
              no_widgets: [OFF,ON]
              no_gui: [OFF,ON]
              many_roles: [OFF,ON]
        steps:
          - name: Install Dependencies
            run: |
              sudo apt-get update -y
              sudo apt-get install libxcb-icccm4 libxcb-xkb1 libxcb-icccm4 libxcb-image0 libxcb-render-util0 libxcb-randr0 libxcb-keysyms1 libxcb-xinerama0 libxcb-xinput-dev
              export PATH=$PATH:$PWD/build/x64/lib
              export PATH=$PATH:$PWD/build/x64/bin
          - name: Install Qt
            uses: jurplel/install-qt-action@v2
            with:
              version: ${{ matrix.qt_ver }}
              host: 'linux'
              target: 'desktop'
          - uses: actions/checkout@v2
          - name: Create Build Directory
            run: |
              mkdir build
          - name: Debug Build Qt ${{ matrix.qt_ver }} Static:${{ matrix.static_lib }} No Gui:${{ matrix.no_gui }} No Widgets:${{ matrix.no_widgets }} Many Roles:${{ matrix.many_roles }}
            run: |
              cd build
              cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_TESTING=ON -DBUILD_EXAMPLES=OFF -DBUILD_STATIC_LIBS=${{ matrix.static_lib }} -DCMAKE_INSTALL_PREFIX="./installed" -DNO_WIDGETS=${{ matrix.no_widgets }} -DNO_GUI=${{ matrix.no_gui }} -DOPTIMISE_FOR_MANY_ROLES=${{ matrix.many_roles }} ../
              cmake --build .
              cmake --build . --target install
          - name: Test Debug
            uses: GabrielBB/xvfb-action@v1
            with:
              working-directory: ./build
              run: ctest --verbose
          - name: Release Build Qt ${{ matrix.qt_ver }} Static:${{ matrix.static_lib }} No Gui:${{ matrix.no_gui }} No Widgets:${{ matrix.no_widgets }} Many Roles:${{ matrix.many_roles }}
            run: |
              cd build
              cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON -DBUILD_STATIC_LIBS=${{ matrix.static_lib }} -DCMAKE_INSTALL_PREFIX="./installed" -DNO_WIDGETS=${{ matrix.no_widgets }} -DNO_GUI=${{ matrix.no_gui }} -DOPTIMISE_FOR_MANY_ROLES=${{ matrix.many_roles }} ../
              cmake --build .
              cmake --build . --target install
          - name: Test Release
            uses: GabrielBB/xvfb-action@v1
            with:
              working-directory: ./build
              run: ctest --verbose
          